### ISSUE TITLE
Can't get DCP2.2 to decensor on Arch Linux

### ISSUE THREAD

**Issue by Babyforce** [deeppomf/DeepCreamPy#177]
**Describe the bug**
When I try to decensor images through the GUI, I get errors in a terminal and it doesn't do anything else.
Once I click the decensor button on the GUI, I get this in my terminal :
`load_model()
2019-11-03 13:27:15.792152: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2019-11-03 13:27:15.796276: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcuda.so.1
2019-11-03 13:27:15.874894: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:1005] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2019-11-03 13:27:15.876501: I tensorflow/compiler/xla/service/platform_util.cc:197] StreamExecutor cuda device (1) is of insufficient compute capability: 3.5 required, device is 3.0
2019-11-03 13:27:15.908876: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:1005] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2019-11-03 13:27:15.909452: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x7f9e1808aec0 executing computations on platform CUDA. Devices:
2019-11-03 13:27:15.909466: I tensorflow/compiler/xla/service/service.cc:175]   StreamExecutor device (0): GeForce GTX 1060 3GB, Compute Capability 6.1
Traceback (most recent call last):
  File "/home/babyforce/DeepCreamPy-2.2.0-beta/decensor.py", line 61, in run
    self.decensor_all_images_in_folder()
  File "/home/babyforce/DeepCreamPy-2.2.0-beta/decensor.py", line 84, in decensor_all_images_in_folder
    self.load_model()
  File "/home/babyforce/DeepCreamPy-2.2.0-beta/decensor.py", line 80, in load_model
    is_mosaic=self.is_mosaic)
  File "/home/babyforce/DeepCreamPy-2.2.0-beta/model.py", line 22, in __init__
    self.build_model()
  File "/home/babyforce/DeepCreamPy-2.2.0-beta/model.py", line 89, in build_model
    self.sess = tf.Session(config=config)
  File "/home/babyforce/.python_venv/DCP2.2/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1570, in __init__
    super(Session, self).__init__(target, graph, config=config)
  File "/home/babyforce/.python_venv/DCP2.2/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 693, in __init__
    self._session = tf_session.TF_NewSessionRef(self._graph._c_graph, opts)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Invalid device ordinal value (1). Valid range is [0, 0].
        while setting up XLA_GPU_JIT device number 1` 

**To Reproduce**
1. Launch the GUI of DCP from a terminal in a python venv.
2. Click on 'Decensor your images'

**Expected behavior**
It should decensor my images without any errors.

**Screenshots**
![error_dcp](https://user-images.githubusercontent.com/1695422/68085338-49bd1000-fe40-11e9-9b64-ebf136c7536f.png)
It just gets stuck here.

**Installation method**
I launch DCP2.2 from a Python 3.6.9 virtual environment, in which I installed both requirement-cpu.txt and requirement-gpu.txt using "pip -r 'file.txt'". I then launch the software with the "python main.py", still from the python venv.

**Desktop (please complete the following information):**
 - OS: Arch Linux
 - Version : Latest
 - Supports AVX? I guess so.

**Additional context**
I have no idea what's causing this, it works perfectly on Windows, even with both of my GPUs (I have a GTX 1060 3GB and a GTX 760 2GB, I guess both can run tensorflow as well). Am I doing something wrong or am I missing something? Older version of DCP run just fine, so I would say this is caused by the GPU version of tensorflow?

**Comment by deeppomf** [comment]
Have you tried with a fresh virtualenv with installing requirement-gpu.txt only?

**Comment by Babyforce** [comment]
> Have you tried with a fresh virtualenv with installing requirement-gpu.txt only?

I tried with only installing the requirement-gpu.txt and it gave me the same error. However, it worked by only installing requirement-cpu.txt, but it's losing decensor speed and quality I suppose. If both are installed, I get the same error as with the requirement-gpu.txt only. That's really strange. Did all of this in different python 3.6 venv.

**Comment by Kadantte** [comment]
@Babyforce When you run DCP 2.2 did u use your GPUs at the same time? If yes please try to remove one then try DCP 2.2 Again, since there's a problem at using two GPUs at the same time. Also, the problem was caused by TensorFlow, not by DCP 2.2, I hope this will help you.

**Comment by Babyforce** [comment]
> @Babyforce When you run DCP 2.2 did u use your GPUs at the same time? If yes please try to remove one then try DCP 2.2 Again, since there's a problem at using two GPUs at the same time. Also, the problem was caused by TensorFlow, not by DCP 2.2, I hope this will help you.

I only use a single GPU at a time. I used to do some PCi Passthrough, hence why I have a second GPU, but since I've got problems with Xorg, I can't change the display GPU, so my first (1060) displays and handles everything and the second one is basically idle (Although I can try to disable it using a kernel option). I also feared this was coming from Tensorflow since it is mentioned in the error message, thanks for clarifying.
Will report back once I've tested.
